---
title: "Kickstarter"
author: "Pouria Niknam"
date: "5/9/2020"str
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE,echo=FALSE,warning=FALSE}
library(dplyr)
library(readr)
library(lubridate)
library(stringr)
library(tree)
library(randomForest)
library(gbm)
library(nnet)
library(NeuralNetTools)
```

```{r, eval=FALSE}
kickstart <- list.files(path="C:\\Users\\Pouria\\OneDrive - UWGB\\Documents\\Kickstarter", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows
```
```{r, eval=FALSE}
write_csv(kickstart,pa th="C:\\Users\\Pouria\\OneDrive - UWGB\\Documents\\Kickstarter.csv")
```
```{r, message=FALSE,echo=FALSE,warning=FALSE}
kickstart <- read_csv("C:\\Users\\Pouria\\OneDrive - UWGB\\Documents\\Kickstarter.csv")
```

```{r}
kickstart$deadline <- as_datetime(kickstart$deadline)
kickstart$launched_at <- as_datetime(kickstart$launched_at)
kickstart$state_changed_at <- as_datetime(kickstart$state_changed_at)

kickstart$live_period <- as.integer(difftime(kickstart$deadline, kickstart$launched_at, units = "days"))
kickstart$state_change_period <- as.integer(difftime(kickstart$state_changed_at, kickstart$launched_at, units = "days"))

kickstart$country <- as.factor(kickstart$country)
kickstart$currency <- as.factor(kickstart$currency)
kickstart <- subset(kickstart, kickstart$state != "live")
kickstart$state <- as.factor(kickstart$state)


kickstart$usd_goal <- kickstart$goal*kickstart$static_usd_rate
```

```{r}
kickstart <- kickstart[,-c(2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,34,35,36,38)]
```

```{r}
test <- lapply(kickstart$category, strsplit, ",")
n = length(test)
test.df = matrix(data = NA, nrow = n, ncol = 2)
test.matrix = matrix(data = NA, nrow = n, ncol = 2)
for (i in 1:n){
  test.df[i, 1] <- test[[i]][[1]][3]
  test.df[i, 2] <- test[[i]][[1]][6]
}
test.df <- as.data.frame(test.df)
names(test.df)[1] <- "Category"
names(test.df)[2] <- "Main.Category"

cat <- lapply(test.df$Category, strsplit, ":")
mcat <- lapply(test.df$Main.Category, strsplit, ":")
for (j in 1:n){
  test.matrix[j, 1] <- cat[[j]][[1]][2]
  test.matrix[j, 2] <- mcat[[j]][[1]][2]
}

test.df <- as.data.frame(test.matrix)
names(test.df)[1] <- "Category"
names(test.df)[2] <- "Main.Category"
category <- rep(1:n)
main.category <- rep(1:n)
for (k in 1:n){
  category[k] <- gsub('"', '', test.df$Category[k], fixed = TRUE)
  main.category[k] <- gsub('"', '', test.df$Main.Category[k], fixed = TRUE)
}
```

```{r}
kickstart$category <- category
kickstart$main.category <- main.category
```

```{r}
for (l in 1:n){
  if (kickstart$main.category[l] == "{web"){
    if (kickstart$category[l] == "fashion") {
      kickstart$main.category[l] = "Fashion"
    } else if (kickstart$category[l] == "technology") {
      kickstart$main.category[l] = "Technology"
    } else if (kickstart$category[l] == "music") {
      kickstart$main.category[l] = "Music"
    } else if (kickstart$category[l] == "theater") {
      kickstart$main.category[l] = "Theater"
    } else if (kickstart$category[l] == "food") {
      kickstart$main.category[l] = "Food"
    } else if (kickstart$category[l] == "journalism") {
      kickstart$main.category[l] = "Journalism"
    } else if (kickstart$category[l] == "design") {
      kickstart$main.category[l] = "Design"
    } else if (kickstart$category[l] == "publishing") {
      kickstart$main.category[l] = "Publishing"
    } else if (kickstart$category[l] == "art") {
      kickstart$main.category[l] = "Art"
    } else if (kickstart$category[l] == "comics") {
      kickstart$main.category[l] = "Comics"
    } else if (kickstart$category[l] == "photography") {
      kickstart$main.category[l] = "Photography"
    } else if (kickstart$category[l] == "crafts") {
      kickstart$main.category[l] = "Crafts"
    } else if (kickstart$category[l] == "dance") {
      kickstart$main.category[l] = "Dance"
    } else if (kickstart$category[l] == "film & video") {
      kickstart$main.category[l] = "Film & Video"
    }
  }
}
```

```{r}
kickstart$category <- as.factor(kickstart$category)
kickstart$main.category <- as.factor(kickstart$main.category)
```

```{r, eval=FALSE}
write_csv(kickstart, "kickstarter.clean.csv")
```

```{r, eval=FALSE}
summary(kickstart)
```

```{r, message=FALSE,echo=FALSE,warning=FALSE}
#kickstart <- read_csv("kickstarter.clean.csv")
```

```{r}
hist(kickstart$backers_count)
hist(kickstart$usd_pledged)
hist(kickstart$usd_goal)
```

```{r}
boxplot(kickstart$backers_count)
boxplot(kickstart$usd_pledged)
boxplot(kickstart$usd_goal)
```

```{r}
hist(kickstart$live_period)
hist(kickstart$state_change_period)
```

```{r}
set.seed(7, sample.kind = "Rounding")
train = sample(1:n, round(n/5), replace = F)
ks.tree <- tree(state ~ ., data = kickstart[train,-2])
summary(ks.tree)
```

```{r}
plot(ks.tree)
text(ks.tree, pretty = 0)
```

```{r}
item.pred <- predict(ks.tree, kickstart[-train,], type = "class")
table(item.pred, kickstart$state[-train])
```
```{r}
1880/(5015+58039+95420)
```

```{r}
kickstart.cv <- cv.tree(ks.tree, FUN = prune.misclass)
kickstart.cv
plot(kickstart.cv)
kickstart.cv$size[which(kickstart.cv$dev == min(kickstart.cv$dev))]
```

```{r}
ks.mat <- model.matrix(state~., data = kickstart)
ks.df <- data.frame(cbind(ks.mat[,-1], kickstart$state))
ks.df$V211 <- as.factor(ks.df$V211)
names(ks.df)[211] <- "state"
```

```{r}
set.seed(37, sample.kind = "Rounding")
train2 = sample(1:n, round(n/5), replace = F)
ks.tree2 <- tree(state ~ ., data = ks.df[train2,-1])
summary(ks.tree2)
```

```{r}
plot(ks.tree2)
text(ks.tree2, pretty = 0)
```


```{r}
kickstart.cv <- cv.tree(ks.tree2, FUN = prune.misclass)
kickstart.cv
plot(kickstart.cv)
kickstart.cv$size[which(kickstart.cv$dev == min(kickstart.cv$dev))]
```
```{r}
item.pred2 <- predict(ks.tree2, ks.df[-train,], type = "class")
table(item.pred2, ks.df$state[-train])
```

```{r}
ks.mat <- kickstart[,-2]
ks.mat <- model.matrix(state~., data = ks.mat)
ks.mat <- scale(ks.mat)
ks.df <- data.frame(cbind(ks.mat[,-1], kickstart$state))
ks.df$V43 <- as.factor(ks.df$V43)
names(ks.df)[43] <- "state"
```

```{r, eval=FALSE}
set.seed(69, sample.kind = "Rounding")
valid = sample(1:n, round(n/5), replace = F)
train = c(1:n)[-valid]
train.nnet = ks.df[train,]
valid.nnet = ks.df[valid,]
nnet.fit <- nnet(state ~ ., data = train.nnet, size = 10, maxit = 1000, trace = F, decay = 0.001)
````

```{r, eval=FALSE}
nnet.pred <- predict(nnet.fit, valid.nnet, type = "class")
pred.error = sum(nnet.pred != valid.nnet$state)/dim(valid.nnet)[1]
pred.error
table(nnet.pred, valid.nnet$state)
```

```{r, eval=FALSE}
plotnet(nnet.fit)
```

```{r}
set.seed(67, sample.kind = "Rounding")
valid = sample(1:n, round(n/10), replace = F)
train = c(1:n)[-valid]
train.nnet = ks.df[train,]
valid.nnet = ks.df[valid,]
````

```{r}
i=1
j=1
sizes = seq(1, 50, 1)
decayRate = seq(0, 1, .01)
pred.error = matrix(data=NA,nrow=length(sizes),ncol=length(decayRate))
set.seed(63, sample.kind = "Rounding")
# Training neural networks with different number of hidden nodes to find the number of nodes resulting in the lowest error. 
for (i in 1:length(sizes)) {
  for (j in 1:length(decayRate)){
    ANN.fit <- nnet(state~., data = train.nnet, size = sizes[i], maxit = 10000, trace = F, decay = decayRate[j])
    ANN.pred <- predict(ANN.fit, valid.nnet, type = "class")
    pred.error[i,j] = sum(ANN.pred != valid.nnet$state)/dim(valid.nnet)[1]
  }
}
```

```{r}
min(pred.error)
best.size.ANN <- arrayInd(which.min(pred.error), dim(pred.error)) 
```

```{r fig.height=20, fig.width=20}
best.fit.ANN <- nnet(state~., data = train.nnet, size = best.size.ANN[1], maxit = 10000, trace = F, decay = best.size.ANN[2])
# Creates a plot fo the neural network with the optimum values
plotnet(best.fit.ANN)
```
