---
title: "Unused Code"
author: "Pouria Niknam"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE,echo=FALSE,warning=FALSE,eval=FALSE}
set.seed(2, sample.kind = "Rounding")
n = dim(kickstart[1])
sample.list <- sample.int(n, size = 5000, replace = FALSE)
ks.sample <- kickstart[sample.list,]
```
```{r, eval=FALSE}
write_csv(ks.sample,path="C:\\Users\\Pouria\\OneDrive - UWGB\\Documents\\ks.sample.csv")
```

```{r, message=FALSE,echo=FALSE,warning=FALSE}
ks.sample <- read_csv("C:\\Users\\Pouria\\OneDrive - UWGB\\Documents\\ks.sample.csv")
```

```{r}
ks.sample$deadline <- as_datetime(ks.sample$deadline)
ks.sample$launched_at <- as_datetime(ks.sample$launched_at)
ks.sample$state_changed_at <- as_datetime(ks.sample$state_changed_at)

ks.sample$live_period <- as.integer(difftime(ks.sample$deadline, ks.sample$launched_at, units = "days"))
ks.sample$state_change_period <- as.integer(difftime(ks.sample$state_changed_at, ks.sample$launched_at, units = "days"))

ks.sample$country <- as.factor(ks.sample$country)
ks.sample$currency <- as.factor(ks.sample$currency)
ks.sample <- subset(ks.sample, ks.sample$state != "live")
ks.sample$state <- as.factor(ks.sample$state)


ks.sample$usd_goal <- ks.sample$goal*ks.sample$static_usd_rate
```

```{r}
ks.sample <- ks.sample[,-c(2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,34,35,36,38)]
```

```{r}
summary(ks.sample)
write_csv(ks.sample, "ks.sample.clean.csv")
```

```{r}
summary(kickstart)
write_csv(kickstart, "kickstarter.clean.csv")
```

```{r, message=FALSE,echo=FALSE,warning=FALSE}
kickstart <- read_csv("kickstarter.clean.csv")
```

```{r}
# Using Box-Cox transform to reduce skewedness
box.backers <- EnvStats::boxcox(kickstart$backers_count + 1)
best.lambda.backers <- box.backers$lambda[which.max(box.backers$objective)]
kickstart$box.backers <- boxcoxTransform(kickstart$backers_count + 1, best.lambda.backers)

box.pledged <- EnvStats::boxcox(kickstart$usd_pledged + 1)
best.lambda.pledged <- box.pledged$lambda[which.max(box.pledged$objective)]
kickstart$box.pledged <- boxcoxTransform(kickstart$usd_pledged + 1, best.lambda.pledged)

box.goal <- EnvStats::boxcox(kickstart$usd_goal + 1)
best.lambda.goal <- box.goal$lambda[which.max(box.goal$objective)]
kickstart$box.goal <- boxcoxTransform(kickstart$usd_goal + 1, best.lambda.goal)
```

```{r}
hist(kickstart$box.backers)
hist(kickstart$box.pledged)
hist(kickstart$box.goal)
```

```{r}
kickstart.lm <- kickstart[,-c(1,7,10)]
len <- dim(kickstart.lm)[1]
```

```{r}
plot(kickstart.lm$box.goal ~ kickstart.lm$box.backers)
plot(kickstart.lm$box.goal ~ kickstart.lm$box.pledged)
```



```{r}
set.seed(37, sample.kind = "Rounding")
groupi = sample(len, round(len/5), replace = FALSE)
```

```{r}
fit <- glm(state~., data = kickstart.lm[groupi,], family = "binomial")
```

```{r}
#system.time(regfit.full <- regsubsets(state~., data = kickstart.lm[groupi,], nvmax = 50, really.big = TRUE))
```





